server:
    tomcat:
      uri-encoding: utf-8
    port: 8080

spring:
    redis:
      port: 7000
      host: 127.0.0.1
      password: 111111
      pool:
        max-active: 100
        max-idle: 5
        max-wait: 60000


    aop:
      auto: true

    datasource:
      url: jdbc:mysql://localhost:3306/xxl-job?useSSL=false
      username: root
      password: 111111
      driver-class-name: com.mysql.jdbc.Driver

    jpa:
      show-sql: true

